# Generated by Django 4.1.7 on 2023-03-18 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_alter_doctors_doc_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='patien_email',
            new_name='patient_email',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='patien_name',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='patien_phone',
            new_name='patient_phone',
        ),
    ]
